# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: actions-setup-redis
      # Startup a Redis server to test with
      uses: shogo82148/actions-setup-redis@v1.42.0
      with:
        # the distribution of redis
        distribution: redis
        # the version of redis
        redis-version: latest
        # the port of redis-sever
        redis-port: 6379
        # the tls port of redis-sever
        redis-tls-port: 0
        # enable to auto-start redis-sever
        auto-start: true
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude experiments,design
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude experiments,design
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest --ignore=tests/test_image_to_3d.py
